### ISSUE TITLE
Implement a VUE frontend

### ISSUE THREAD

**Issue by sebastianmonten** [IFCViz/vercel-test#2]
Description: Implement a "drag and drop" interface for client, and implement a listing of the data from the IFC file to be displayed after the parsing by the server. 

Definition of done: A working drag and drop interface and a working listing functionality

Testing: Provide a non-valid IFC-file to the interface, try different IFC files with varying sizes.

**Comment by Dudjfy** [comment]
Chose to implement it in another way in the end
