### ISSUE TITLE
Extraction of floor area assumes that `BaseQuantities` exists in the json but that is not always the case

### ISSUE THREAD

**Issue by sebastianmonten** [IFCViz/vercel-test#5]
Descrition:

https://github.com/IFCViz/vercel-test/blob/ae6ff5a52bb7db6a4e99c4540caed396de8d34f2/api/index.py#L94C3-L94C49?plain=1

`"BaseQuantities"`does not seem to be present in all IFC-files. Is this standard, should `"BaseQuantities" exist? If not, we need to find a new way to extract area from the json. 

Definition of done: A draft of a new way to extract floor are from json and create a new issue for implementing it.

**Comment by Dudjfy** [comment]
Added a couple other ways to parse, seems to work for all the relevant files tested
